-- ============================================
-- V2 Migration: Add shared words & wordlists tables
-- Run in Supabase Dashboard → SQL Editor
-- ============================================

-- 1. Shared wordlists table (no RLS - all users share built-in lists)
CREATE TABLE IF NOT EXISTS wordlists (
  id serial PRIMARY KEY,
  name text NOT NULL,
  source text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- 2. Shared words table (no RLS - all users share)
CREATE TABLE IF NOT EXISTS words (
  id serial PRIMARY KEY,
  wordlist_id integer REFERENCES wordlists(id) ON DELETE CASCADE NOT NULL,
  word text NOT NULL,
  meaning_cn text,
  unit text,
  phonetic text DEFAULT '',
  example1 text DEFAULT '',
  example2 text DEFAULT '',
  source text DEFAULT ''
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS idx_words_wordlist ON words(wordlist_id);
CREATE INDEX IF NOT EXISTS idx_words_word ON words(word);
CREATE INDEX IF NOT EXISTS idx_uws_word_text ON user_word_state(word_text);
CREATE INDEX IF NOT EXISTS idx_uws_user_id ON user_word_state(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);

-- 4. Seed wordlists
INSERT INTO wordlists (id, name, source) VALUES (1, '七年级上册（外研版）', 'waiyanbanseven_a');
INSERT INTO wordlists (id, name, source) VALUES (2, '七年级下册（外研版）', 'waiyanbanseven_b');
SELECT setval('wordlists_id_seq', 2);

-- 5. Seed words (generated from grade7a.js and grade7b.js)
-- See seed_words.sql for 446 INSERT statements
-- Copy-paste the content of seed_words.sql below this line, or run:
--   \i seed_words.sql
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'ready', '准备好（做某事）的', 'Starter', 'Are you ready for the new term?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'textbook', '教科书；教材', 'Starter', 'Please open your textbook to page 10.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'eraser', '橡皮', 'Starter', 'Can I borrow your eraser?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'junior high', '初级中学', 'Starter', 'I study in a junior high school.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'geography', '地理', 'Starter', 'My favorite subject is geography.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'biology', '生物', 'Starter', 'We have a biology class on Wednesday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'history', '历史', 'Starter', 'History is very interesting.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'physics', '物理', 'Starter', 'Physics is a difficult subject for me.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'chemistry', '化学', 'Starter', 'We do experiments in chemistry class.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'hello', '你好；喂', 'Starter Unit 1', 'Hello, my name is Li Ming.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'class', '同学；班级', 'Starter Unit 1', 'Good morning, class!', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'my', '我的', 'Starter Unit 1', 'This is my new friend.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'name', '名字', 'Starter Unit 1', 'What''s your name?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'is', '是（be动词第三人称单数）', 'Starter Unit 1', 'He is a student.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Miss', '小姐；老师', 'Starter Unit 1', 'Miss Wang teaches us English.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'good', '好的', 'Starter Unit 1', 'That''s a good idea.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'morning', '早晨；上午', 'Starter Unit 1', 'Good morning, everyone!', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'good morning', '早上好', 'Starter Unit 1', 'Good morning, Mr. Li.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'afternoon', '下午', 'Starter Unit 1', 'Good afternoon, my dear.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'good afternoon', '下午好', 'Starter Unit 1', 'Good afternoon, how are you?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'goodbye', '再见', 'Starter Unit 1', 'Goodbye, see you tomorrow.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Mr.', '先生', 'Starter Unit 1', 'Mr. Zhang is our math teacher.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'and', '和；与', 'Starter Unit 1', 'I have a pen and a pencil.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'this', '这；这个', 'Starter Unit 1', 'This is my schoolbag.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'she', '她', 'Starter Unit 1', 'She is my sister.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'he', '他', 'Starter Unit 1', 'He is from America.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'teacher', '老师', 'Starter Unit 1', 'Our teacher is very kind.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'friend', '朋友', 'Starter Unit 1', 'Tom is my best friend.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'her', '她的', 'Starter Unit 1', 'Her name is Lucy.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'his', '他的', 'Starter Unit 1', 'His favorite color is blue.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'nice', '令人愉快的；宜人的', 'Unit 1', 'It''s nice to meet you.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'to', '用于构成动词不定式；向', 'Unit 1', 'I want to go to the park.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'meet', '遇见；结识', 'Unit 1', 'Pleased to meet you.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'you', '你；你们', 'Unit 1', 'How are you?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'too', '也；太', 'Unit 1', 'I like apples too.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Ms', '女士', 'Unit 1', 'Ms. Chen is our new teacher.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'what', '什么', 'Unit 1', 'What''s your favorite sport?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'your', '你的；你们的', 'Unit 1', 'What''s your name?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'please', '请', 'Unit 1', 'Please sit down.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'sorry', '对不起；抱歉', 'Unit 1', 'Sorry, I''m late.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'can', '能；会', 'Unit 1', 'Can you speak English?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'spell', '拼写', 'Unit 1', 'Can you spell this word?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'it', '它', 'Unit 1', 'It is a cat.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'yes', '是；是的', 'Unit 1', 'Yes, I can.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'thank', '谢谢', 'Unit 1', 'Thank you very much.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'how', '怎样；如何', 'Unit 1', 'How old are you?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'are', '是（be动词复数和第二人称）', 'Unit 1', 'You are my good friend.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'fine', '健康的；美好的', 'Unit 1', 'I''m fine, thank you.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'thanks', '感谢；谢谢', 'Unit 1', 'Thanks for your help.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'mother', '母亲；妈妈', 'Unit 2', 'My mother is a doctor.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'father', '父亲；爸爸', 'Unit 2', 'My father works in a hospital.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'parent', '父；母（复数parents）', 'Unit 2', 'My parents love me very much.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'sister', '姐；妹', 'Unit 2', 'I have a younger sister.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'brother', '兄；弟', 'Unit 2', 'My brother is 10 years old.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'grandmother', '（外）祖母；奶奶；外婆', 'Unit 2', 'My grandmother often tells me stories.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'grandfather', '（外）祖父；爷爷；外公', 'Unit 2', 'My grandfather likes reading newspapers.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'grandparent', '（外）祖父/母（复数grandparents）', 'Unit 2', 'I visit my grandparents every weekend.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'family', '家庭；家人', 'Unit 2', 'I have a big family.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'photo', '照片；相片', 'Unit 2', 'This is a photo of my family.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'these', '这些', 'Unit 2', 'These are my books.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'they', '他们；她们；它们', 'Unit 2', 'They are my classmates.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'mum', '妈妈（口语）', 'Unit 2', 'Mum, I''m hungry.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'dad', '爸爸（口语）', 'Unit 2', 'Dad, can I watch TV?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'left', '左边；左侧', 'Unit 2', 'The library is on the left.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'on the left', '在左边', 'Unit 2', 'My house is on the left of the street.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'right', '右边；右侧', 'Unit 2', 'The school is on the right.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'on the right', '在右边', 'Unit 2', 'The bank is on the right.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'who', '谁', 'Unit 2', 'Who is that girl?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'woman', '成年女子；妇女', 'Unit 2', 'That woman is my aunt.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'aunt', '姑母；姨母；伯母；婶母；舅母', 'Unit 2', 'My aunt is a teacher.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'uncle', '叔父；伯父；舅父；姑父；姨父', 'Unit 2', 'My uncle is a driver.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'cousin', '堂兄（弟、姊、妹）；表兄（弟、姊、妹）', 'Unit 2', 'My cousin lives in Beijing.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'daughter', '女儿', 'Unit 2', 'She has a daughter and a son.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'son', '儿子', 'Unit 2', 'His son is a student.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'doctor', '医生', 'Unit 3', 'My father is a doctor.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'worker', '工人', 'Unit 3', 'He works as a worker in a factory.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'manager', '经理', 'Unit 3', 'The manager of the company is very young.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'nurse', '护士', 'Unit 3', 'She is a nurse in a hospital.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'policeman', '警察（男）', 'Unit 3', 'The policeman helped me find my way.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'policewoman', '警察（女）', 'Unit 3', 'The policewoman caught the thief.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'driver', '司机；驾驶员', 'Unit 3', 'My uncle is a taxi driver.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'farmer', '农民', 'Unit 3', 'The farmer grows vegetables.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'cook', '厨师；烹饪', 'Unit 3', 'My mother is a good cook.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'office', '办公室', 'Unit 3', 'The teacher is in the office.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'hospital', '医院', 'Unit 3', 'I went to the hospital yesterday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'hotel', '宾馆；酒店', 'Unit 3', 'We stayed in a big hotel.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'school', '学校', 'Unit 3', 'I go to school by bike.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'classroom', '教室', 'Unit 3', 'Our classroom is big and bright.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'library', '图书馆', 'Unit 3', 'You can borrow books from the library.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'book', '书', 'Unit 4', 'I have many story books.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'pen', '钢笔', 'Unit 4', 'Can I borrow your pen?', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'pencil', '铅笔', 'Unit 4', 'I need a pencil to draw.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'bag', '包；书包', 'Unit 4', 'My bag is blue.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'chair', '椅子', 'Unit 4', 'Please sit on the chair.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'desk', '书桌；桌子', 'Unit 4', 'There is a computer on the desk.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'map', '地图', 'Unit 4', 'Look at the map of China.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'picture', '图片；照片', 'Unit 4', 'This is a picture of my family.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'computer', '电脑；计算机', 'Unit 4', 'I use a computer to study.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'mouse', '鼠标', 'Unit 4', 'The mouse is next to the keyboard.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'keyboard', '键盘', 'Unit 4', 'Please type on the keyboard.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'screen', '屏幕', 'Unit 4', 'The screen is very big.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'apple', '苹果', 'Unit 4', 'This is an apple.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'banana', '香蕉', 'Unit 4', 'I like bananas very much.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'orange', '橙子；橘子', 'Unit 4', 'An orange a day keeps the doctor away.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'pear', '梨', 'Unit 4', 'This pear is sweet.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'watermelon', '西瓜', 'Unit 4', 'Watermelon is my favorite fruit.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'milk', '牛奶', 'Unit 4', 'I drink milk every morning.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'bread', '面包', 'Unit 4', 'I have bread for breakfast.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'rice', '米饭', 'Unit 4', 'We eat rice for lunch.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'noodle', '面条', 'Unit 4', 'I like eating noodles.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'meat', '肉', 'Unit 4', 'My father likes eating meat.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'chicken', '鸡肉；鸡', 'Unit 4', 'I want some chicken for dinner.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'fish', '鱼；鱼肉', 'Unit 4', 'Fish is good for our health.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'vegetable', '蔬菜', 'Unit 4', 'We should eat more vegetables.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'potato', '土豆；马铃薯', 'Unit 4', 'I like potato chips.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'tomato', '西红柿；番茄', 'Unit 4', 'Tomato is a kind of vegetable.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'day', '天；日', 'Unit 5', 'Today is a sunny day.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'week', '星期；周', 'Unit 5', 'There are seven days in a week.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Monday', '星期一', 'Unit 5', 'We have math on Monday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Tuesday', '星期二', 'Unit 5', 'I have a piano lesson on Tuesday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Wednesday', '星期三', 'Unit 5', 'Wednesday is my favorite day.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Thursday', '星期四', 'Unit 5', 'We have PE on Thursday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Friday', '星期五', 'Unit 5', 'Friday is the last day of the week.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Saturday', '星期六', 'Unit 5', 'I play football on Saturday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'Sunday', '星期日', 'Unit 5', 'I go to the park on Sunday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'get up', '起床', 'Unit 5', 'I get up at 6:30 every morning.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'go to school', '去上学', 'Unit 5', 'I go to school by bus.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'have', '有；上（课）', 'Unit 5', 'We have English class in the morning.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'lesson', '课；一节课', 'Unit 5', 'We have four lessons in the morning.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'break', '休息；课间休息', 'Unit 5', 'We have a 10-minute break.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'lunch', '午餐；午饭', 'Unit 5', 'I have lunch at school.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'go home', '回家', 'Unit 5', 'I go home at 5:00 p.m.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'do', '做；干', 'Unit 5', 'I do my homework every evening.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'homework', '家庭作业', 'Unit 5', 'I finish my homework before dinner.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'go to bed', '上床睡觉', 'Unit 5', 'I go to bed at 9:30 p.m.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'zoo', '动物园', 'Unit 6', 'We go to the zoo on Sunday.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'animal', '动物', 'Unit 6', 'I like all kinds of animals.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'panda', '熊猫', 'Unit 6', 'Pandas are very cute.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'monkey', '猴子', 'Unit 6', 'Monkeys like bananas.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'tiger', '老虎', 'Unit 6', 'Tigers are very dangerous.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'lion', '狮子', 'Unit 6', 'The lion is the king of the forest.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'elephant', '大象', 'Unit 6', 'Elephants have long noses.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'giraffe', '长颈鹿', 'Unit 6', 'Giraffes have long necks.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'bird', '鸟', 'Unit 6', 'The bird is singing in the tree.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'fish', '鱼', 'Unit 6', 'There are many fish in the river.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'snake', '蛇', 'Unit 6', 'Snakes are cold-blooded animals.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'zebra', '斑马', 'Unit 6', 'Zebras have black and white stripes.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'panda', '熊猫', 'Unit 6', 'Pandas live in China.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'come from', '来自', 'Unit 6', 'I come from China.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'different', '不同的', 'Unit 6', 'We have different hobbies.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'country', '国家', 'Unit 6', 'China is a big country.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'other', '其他的；另外的', 'Unit 6', 'I like other kinds of fruits.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'all', '所有的；全部的', 'Unit 6', 'All students like PE.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'over there', '在那边', 'Unit 6', 'The monkeys are over there.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'food', '食物', 'Unit 7', 'I like Chinese food.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'drink', '饮料；喝', 'Unit 7', 'I want a drink of water.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'candy', '糖果', 'Unit 7', 'Too much candy is bad for teeth.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'fruit', '水果', 'Unit 7', 'I eat fruit every day.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'vegetable', '蔬菜', 'Unit 7', 'Vegetables are good for health.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'meat', '肉', 'Unit 7', 'I don''t eat meat.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'rice', '米饭', 'Unit 7', 'I have rice for dinner.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'noodle', '面条', 'Unit 7', 'Noodles are my favorite food.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'fish', '鱼肉；鱼', 'Unit 7', 'Fish is delicious.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'chicken', '鸡肉；鸡', 'Unit 7', 'I like chicken soup.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'beef', '牛肉', 'Unit 7', 'Beef is expensive.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'pork', '猪肉', 'Unit 7', 'Pork is the most popular meat in China.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'breakfast', '早餐；早饭', 'Unit 7', 'I have breakfast at 7:00.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'lunch', '午餐；午饭', 'Unit 7', 'I have lunch at school.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'dinner', '晚餐；晚饭', 'Unit 7', 'I have dinner with my family.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'have breakfast', '吃早餐', 'Unit 7', 'I have breakfast every morning.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'have lunch', '吃午餐', 'Unit 7', 'We have lunch at 12:00.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'have dinner', '吃晚餐', 'Unit 7', 'They have dinner at 6:00 p.m.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'like', '喜欢；像', 'Unit 7', 'I like apples.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'favorite', '最喜欢的', 'Unit 7', 'My favorite food is noodles.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'healthy', '健康的', 'Unit 7', 'Vegetables are healthy food.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (1, 'unhealthy', '不健康的', 'Unit 7', 'Junk food is unhealthy.', 'waiyanbanseven_a');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'review', '书评', 'Unit 1', 'I wrote a review for that book.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'chocolate', '巧克力', 'Unit 1', 'I like eating chocolate.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'factory', '工厂', 'Unit 1', 'There is a chocolate factory in my city.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'exciting', '令人兴奋的；使人激动的', 'Unit 1', 'The movie is very exciting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'most', '最；最多', 'Unit 1', 'This is the most interesting book.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'magical', '奇异的；美妙的；迷人的', 'Unit 1', 'The story is very magical.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'part', '部分', 'Unit 1', 'This is an important part of the story.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'side', '边；面；侧', 'Unit 1', 'There is a tree on the side of the road.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'poor', '贫穷的；贫困的', 'Unit 1', 'He comes from a poor family.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'forget', '忘记；遗忘', 'Unit 1', 'Don''t forget to bring your book.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'once', '曾经；一次', 'Unit 1', 'I have been to Beijing once.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'everything', '每件事物；所有事物', 'Unit 1', 'Everything is ready.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'rich', '有钱的；富有的', 'Unit 1', 'He is a rich man.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'choose', '选择', 'Unit 1', 'You can choose any book you like.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'complete', '完成；结束', 'Unit 1', 'I need to complete my homework.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'expression', '词组；表达', 'Unit 1', 'This is a common expression.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'passage', '一段；一节', 'Unit 1', 'Read this passage carefully.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'opinion', '意见；评论', 'Unit 1', 'What''s your opinion about this movie?', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'description', '描述；描写；叙述；形容', 'Unit 1', 'The description is very clear.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'topic', '主题', 'Unit 1', 'The topic of the meeting is about education.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'agree', '同意；赞同', 'Unit 1', 'I agree with you.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'paragraph', '（文章的）段；段落', 'Unit 1', 'This paragraph is very important.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'crayon', '蜡笔', 'Unit 2', 'I draw a picture with crayons.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'eraser', '橡皮擦', 'Unit 2', 'I need an eraser to correct my mistake.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'glove', '手套', 'Unit 2', 'I wear gloves in winter.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'wallet', '钱包', 'Unit 2', 'I lost my wallet yesterday.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'watch', '手表；观看', 'Unit 2', 'I have a new watch.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'whose', '谁的', 'Unit 2', 'Whose book is this?', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'first of all', '首先；第一', 'Unit 2', 'First of all, you need to study hard.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'lose', '丢失；失去', 'Unit 2', 'I lost my key.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'find', '发现；找到', 'Unit 2', 'I can''t find my pen.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'lost and found', '失物招领', 'Unit 2', 'Go to the lost and found office.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'mine', '我的（名词性物主代词）', 'Unit 2', 'This book is mine.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'yours', '你（们）的（名词性物主代词）', 'Unit 2', 'Is this pen yours?', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'his', '他的（名词性物主代词）', 'Unit 2', 'The bag is his.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hers', '她的（名词性物主代词）', 'Unit 2', 'The dress is hers.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'ours', '我们的（名词性物主代词）', 'Unit 2', 'The classroom is ours.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'theirs', '他/她/它们的（名词性物主代词）', 'Unit 2', 'The ball is theirs.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'careful', '小心的；仔细的', 'Unit 2', 'Be careful when you cross the road.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'be careful with', '小心（对待）', 'Unit 2', 'Be careful with your money.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'on', '在……上；关于', 'Unit 2', 'The book is on the desk.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'from', '从；来自', 'Unit 2', 'I am from China.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'mobile phone', '手机', 'Unit 2', 'I have a new mobile phone.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'lost and found box', '失物招领箱', 'Unit 2', 'Put the lost things in the lost and found box.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'in a hurry', '匆忙地', 'Unit 2', 'He left in a hurry.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hundred', '百', 'Unit 2', 'There are hundreds of students in our school.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'thousand', '千', 'Unit 2', 'This tree is thousands of years old.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'strange', '奇怪的；陌生的', 'Unit 2', 'This is a strange place.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'boat', '船', 'Unit 3', 'We go to school by boat.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'bus', '公共汽车', 'Unit 3', 'I take a bus to school.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'car', '小汽车', 'Unit 3', 'My father drives a car to work.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'train', '火车', 'Unit 3', 'I go to Beijing by train.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'plane', '飞机', 'Unit 3', 'I want to fly a plane.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'bike', '自行车', 'Unit 3', 'I ride a bike to school.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'ride', '骑；乘坐', 'Unit 3', 'I ride my bike to the park.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'subway', '地铁', 'Unit 3', 'Take the subway to the city center.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'ship', '轮船', 'Unit 3', 'We travel by ship.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'taxi', '出租车', 'Unit 3', 'Take a taxi to the airport.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'journey', '旅行；旅程', 'Unit 3', 'Have a good journey!', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hour', '小时', 'Unit 3', 'It takes me an hour to get to school.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'minute', '分钟', 'Unit 3', 'Wait a minute, please.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'second', '秒；第二', 'Unit 3', 'One minute has sixty seconds.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'kilometer', '千米；公里', 'Unit 3', 'My home is two kilometers from school.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'far', '远；遥远的', 'Unit 3', 'My school is far from my home.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'near', '近；附近', 'Unit 3', 'My home is near the school.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'close', '近的；靠近的', 'Unit 3', 'The shop is close to my home.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'by', '乘；通过', 'Unit 3', 'I go to school by bike.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'walk', '步行；散步', 'Unit 3', 'I walk to school every day.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'drive', '驾驶；开车', 'Unit 3', 'My father drives to work.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'fly', '飞；飞行', 'Unit 3', 'Birds fly in the sky.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'swim', '游泳', 'Unit 3', 'I swim in the river in summer.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'run', '跑；跑步', 'Unit 3', 'I run every morning.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'jump', '跳；跳跃', 'Unit 3', 'The rabbit can jump high.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'climb', '爬；攀登', 'Unit 3', 'The monkey climbs the tree quickly.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'dance', '跳舞；舞蹈', 'Unit 3', 'She can dance well.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'sing', '唱歌', 'Unit 3', 'He sings very well.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'draw', '画；绘画', 'Unit 3', 'I draw a picture.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'write', '写；书写', 'Unit 3', 'I write a letter to my friend.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'read', '读；阅读', 'Unit 3', 'I read a book every night.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'speak', '说；讲', 'Unit 3', 'I speak English every day.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'listen', '听；倾听', 'Unit 3', 'Listen to the teacher carefully.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hear', '听见；听到', 'Unit 3', 'I can hear the bird singing.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'see', '看见；看到', 'Unit 3', 'I see a dog in the street.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'watch', '观看；注视', 'Unit 3', 'I watch TV in the evening.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'like', '喜欢；像', 'Unit 3', 'I like playing football.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'love', '爱；热爱', 'Unit 3', 'I love my parents.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'enjoy', '享受；喜爱', 'Unit 3', 'I enjoy reading books.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hate', '讨厌；憎恨', 'Unit 3', 'I hate rainy days.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'want', '想要；需要', 'Unit 3', 'I want to go to the park.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'need', '需要；必需', 'Unit 3', 'I need a pen.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'can', '能；会', 'Unit 3', 'I can swim.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'could', '能；会（can的过去式）', 'Unit 3', 'I could swim when I was five.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'may', '可以；可能', 'Unit 3', 'May I come in?', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'might', '可能；也许（may的过去式）', 'Unit 3', 'He might come tomorrow.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'must', '必须；一定', 'Unit 3', 'You must finish your homework.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'should', '应该；应当', 'Unit 3', 'You should study hard.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'will', '将；会', 'Unit 3', 'I will go to Beijing tomorrow.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'would', '将；会（will的过去式）', 'Unit 3', 'I would like a cup of tea.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'buy', '买；购买', 'Unit 4', 'I buy a book in the bookstore.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'call', '打电话；称呼', 'Unit 4', 'I call my mother every day.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'drive', '驾驶；开车', 'Unit 4', 'My father drives to work.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'enjoy', '享受；喜爱', 'Unit 4', 'I enjoy the music.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'lie', '躺；平放', 'Unit 4', 'He lies on the bed.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'shop', '逛商店；购物', 'Unit 4', 'I shop with my mother on Sunday.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'take', '拿；取；获得', 'Unit 4', 'Take this book to the classroom.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'take photos', '拍照', 'Unit 4', 'I take photos in the park.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'tell', '告诉；讲述', 'Unit 4', 'Tell me a story.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'wait', '等待；等候', 'Unit 4', 'I wait for you at the school gate.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'for', '为了；给', 'Unit 4', 'This gift is for you.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'wait for', '等待；等候', 'Unit 4', 'Wait for me here.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'at home', '在家', 'Unit 4', 'I stay at home on Sunday.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'at work', '在工作', 'Unit 4', 'My father is at work.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'put on', '穿上；戴上', 'Unit 4', 'Put on your coat.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'take off', '脱下；取下', 'Unit 4', 'Take off your shoes.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'turn on', '打开', 'Unit 4', 'Turn on the light.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'turn off', '关闭', 'Unit 4', 'Turn off the TV.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'up', '向上；朝上', 'Unit 4', 'Stand up, please.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'down', '向下；朝下', 'Unit 4', 'Sit down, please.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'left', '向左；左边', 'Unit 4', 'Turn left at the corner.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'right', '向右；右边', 'Unit 4', 'Turn right at the next crossing.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'straight', '直地；直的', 'Unit 4', 'Go straight ahead.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'along', '沿着；顺着', 'Unit 4', 'Walk along this street.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'across', '穿过；横过', 'Unit 4', 'Cross the road carefully.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'between', '在……之间', 'Unit 4', 'The bank is between the school and the hospital.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'opposite', '在……对面', 'Unit 4', 'The library is opposite the school.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'next to', '紧挨着；旁边', 'Unit 4', 'My home is next to the park.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'in front of', '在……前面', 'Unit 4', 'There is a tree in front of the house.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'behind', '在……后面', 'Unit 4', 'The cat is behind the door.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'above', '在……上方', 'Unit 4', 'The picture is above the desk.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'below', '在……下方', 'Unit 4', 'The ball is below the chair.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'on the left of', '在……的左边', 'Unit 4', 'The bookstore is on the left of the street.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'on the right of', '在……的右边', 'Unit 4', 'The hospital is on the right of the street.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'in the middle of', '在……的中间', 'Unit 4', 'The school is in the middle of the city.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'city', '城市', 'Unit 5', 'Beijing is a big city.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'capital', '首都；省会', 'Unit 5', 'Beijing is the capital of China.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'country', '国家', 'Unit 5', 'China is a great country.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'map', '地图', 'Unit 5', 'Look at the map of the world.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'world', '世界', 'Unit 5', 'We live in the world.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'population', '人口', 'Unit 5', 'The population of China is very large.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'million', '百万', 'Unit 5', 'The city has a population of two million.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'billion', '十亿', 'Unit 5', 'The world has a population of seven billion.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'big', '大的；巨大的', 'Unit 5', 'This is a big apple.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'small', '小的；小', 'Unit 5', 'This is a small cat.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'large', '大的；巨大的', 'Unit 5', 'China is a large country.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'wide', '宽的；宽阔的', 'Unit 5', 'The river is very wide.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'long', '长的；长久的', 'Unit 5', 'The Great Wall is very long.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'high', '高的；高度', 'Unit 5', 'The mountain is very high.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'old', '老的；旧的', 'Unit 5', 'This is an old book.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'new', '新的；新鲜的', 'Unit 5', 'I have a new bike.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'famous', '著名的；出名的', 'Unit 5', 'Beijing is famous for the Great Wall.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'beautiful', '美丽的；漂亮的', 'Unit 5', 'The park is very beautiful.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'interesting', '有趣的；有意思的', 'Unit 5', 'This book is very interesting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'boring', '无聊的；令人厌烦的', 'Unit 5', 'This movie is boring.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'exciting', '令人兴奋的；使人激动的', 'Unit 5', 'The game is exciting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'delicious', '美味的；可口的', 'Unit 5', 'The food is delicious.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hot', '热的；炎热的', 'Unit 5', 'It''s hot in summer.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'cold', '冷的；寒冷的', 'Unit 5', 'It''s cold in winter.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'warm', '温暖的；暖和的', 'Unit 5', 'It''s warm in spring.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'cool', '凉爽的；酷的', 'Unit 5', 'It''s cool in autumn.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'weather', '天气', 'Unit 5', 'What''s the weather like today?', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'spring', '春天；春季', 'Unit 5', 'Spring is my favorite season.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'summer', '夏天；夏季', 'Unit 5', 'I like swimming in summer.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'autumn', '秋天；秋季', 'Unit 5', 'Autumn is a harvest season.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'winter', '冬天；冬季', 'Unit 5', 'I make a snowman in winter.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'season', '季节', 'Unit 5', 'There are four seasons in a year.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'year', '年；年龄', 'Unit 5', 'I am twelve years old.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'month', '月；月份', 'Unit 5', 'There are twelve months in a year.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'week', '星期；周', 'Unit 5', 'There are seven days in a week.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'day', '天；日', 'Unit 5', 'Today is Monday.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hour', '小时', 'Unit 5', 'I study for two hours every day.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'minute', '分钟', 'Unit 5', 'I wait for you for ten minutes.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'second', '秒；第二', 'Unit 5', 'One minute has sixty seconds.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'happy', '高兴的；快乐的', 'Unit 6', 'I am very happy today.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'sad', '难过的；悲哀的', 'Unit 6', 'I am sad because I failed the exam.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'angry', '生气的；愤怒的', 'Unit 6', 'My mother is angry with me.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'afraid', '害怕的；担心的', 'Unit 6', 'I am afraid of dogs.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'excited', '兴奋的；激动的', 'Unit 6', 'I am excited about the trip.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'bored', '感到无聊的；厌烦的', 'Unit 6', 'I am bored with this book.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'tired', '疲倦的；累的', 'Unit 6', 'I am tired after a long walk.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hungry', '饥饿的', 'Unit 6', 'I am hungry now.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'thirsty', '口渴的', 'Unit 6', 'I am thirsty after playing basketball.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'full', '饱的；满的', 'Unit 6', 'I am full after dinner.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'empty', '空的；空洞的', 'Unit 6', 'The bottle is empty.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'good', '好的；优良的', 'Unit 6', 'This is a good idea.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'bad', '坏的；糟糕的', 'Unit 6', 'This is a bad news.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'well', '好；健康的', 'Unit 6', 'I am well today.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'ill', '生病的；不健康的', 'Unit 6', 'He is ill in hospital.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'fine', '健康的；美好的', 'Unit 6', 'I am fine, thank you.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'nice', '令人愉快的；宜人的', 'Unit 6', 'It''s nice to meet you.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'kind', '善良的；友好的', 'Unit 6', 'My teacher is very kind.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'friendly', '友好的；亲切的', 'Unit 6', 'She is friendly to everyone.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'polite', '有礼貌的；客气的', 'Unit 6', 'You should be polite to your teachers.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'rude', '粗鲁的；无礼的', 'Unit 6', 'Don''t be rude to others.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'clever', '聪明的；机灵的', 'Unit 6', 'He is a clever boy.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'foolish', '愚蠢的；傻的', 'Unit 6', 'Don''t be foolish.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'lazy', '懒惰的', 'Unit 6', 'He is a lazy student.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hard-working', '勤奋的；努力工作的', 'Unit 6', 'She is a hard-working girl.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'helpful', '有帮助的；乐于助人的', 'Unit 6', 'He is helpful to his classmates.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'useful', '有用的；有益的', 'Unit 6', 'This book is very useful.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'useless', '无用的；无效的', 'Unit 6', 'This tool is useless.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'important', '重要的；重大的', 'Unit 6', 'English is very important.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'unimportant', '不重要的；无足轻重的', 'Unit 6', 'This thing is unimportant.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'interesting', '有趣的；有意思的', 'Unit 6', 'This story is interesting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'boring', '无聊的；令人厌烦的', 'Unit 6', 'This class is boring.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'exciting', '令人兴奋的；使人激动的', 'Unit 6', 'The match is exciting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'delicious', '美味的；可口的', 'Unit 6', 'The food is delicious.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'terrible', '糟糕的；可怕的', 'Unit 6', 'The weather is terrible today.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'easy', '容易的；简单的', 'Unit 6', 'This question is easy.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'difficult', '困难的；艰难的', 'Unit 6', 'This problem is difficult.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'cheap', '便宜的；廉价的', 'Unit 6', 'This shirt is cheap.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'expensive', '昂贵的；高价的', 'Unit 6', 'This car is expensive.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'big', '大的；巨大的', 'Unit 6', 'This room is big.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'small', '小的；小', 'Unit 6', 'This bag is small.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'long', '长的；长久的', 'Unit 6', 'This river is long.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'short', '短的；矮的', 'Unit 6', 'This pencil is short.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'tall', '高的；高大的', 'Unit 6', 'He is tall.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'short', '矮的；短的', 'Unit 6', 'She is short.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'fat', '胖的；肥的', 'Unit 6', 'The pig is fat.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'thin', '瘦的；薄的', 'Unit 6', 'She is thin.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'strong', '强壮的；坚强的', 'Unit 6', 'He is strong.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'weak', '虚弱的；无力的', 'Unit 6', 'She is weak after illness.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'happy', '幸福的；快乐的', 'Unit 7', 'I have a happy family.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'sad', '悲伤的；难过的', 'Unit 7', 'I am sad because my dog died.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'angry', '愤怒的；生气的', 'Unit 7', 'My father is angry with me.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'afraid', '害怕的；担心的', 'Unit 7', 'I am afraid of snakes.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'excited', '兴奋的；激动的', 'Unit 7', 'I am excited about the party.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'bored', '感到无聊的；厌烦的', 'Unit 7', 'I am bored with this movie.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'tired', '疲倦的；累的', 'Unit 7', 'I am tired after work.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hungry', '饥饿的', 'Unit 7', 'I am hungry now.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'thirsty', '口渴的', 'Unit 7', 'I am thirsty after running.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'full', '饱的；满的', 'Unit 7', 'I am full after lunch.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'empty', '空的；空洞的', 'Unit 7', 'The cup is empty.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'good', '好的；优良的', 'Unit 7', 'This is a good book.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'bad', '坏的；糟糕的', 'Unit 7', 'This is a bad idea.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'well', '好；健康的', 'Unit 7', 'He speaks English well.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'ill', '生病的；不健康的', 'Unit 7', 'She is ill today.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'fine', '健康的；美好的', 'Unit 7', 'I am fine, thank you.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'nice', '令人愉快的；宜人的', 'Unit 7', 'It''s nice to see you.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'kind', '善良的；友好的', 'Unit 7', 'She is a kind girl.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'friendly', '友好的；亲切的', 'Unit 7', 'He is friendly to me.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'polite', '有礼貌的；客气的', 'Unit 7', 'You should be polite to others.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'rude', '粗鲁的；无礼的', 'Unit 7', 'Don''t be rude to your parents.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'clever', '聪明的；机灵的', 'Unit 7', 'He is a clever student.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'foolish', '愚蠢的；傻的', 'Unit 7', 'You are foolish to do that.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'lazy', '懒惰的', 'Unit 7', 'Don''t be lazy.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'hard-working', '勤奋的；努力工作的', 'Unit 7', 'She is hard-working.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'helpful', '有帮助的；乐于助人的', 'Unit 7', 'He is helpful.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'useful', '有用的；有益的', 'Unit 7', 'This tool is useful.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'useless', '无用的；无效的', 'Unit 7', 'This book is useless.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'important', '重要的；重大的', 'Unit 7', 'This is an important meeting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'unimportant', '不重要的；无足轻重的', 'Unit 7', 'This thing is unimportant.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'interesting', '有趣的；有意思的', 'Unit 7', 'This game is interesting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'boring', '无聊的；令人厌烦的', 'Unit 7', 'This class is boring.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'exciting', '令人兴奋的；使人激动的', 'Unit 7', 'The party is exciting.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'delicious', '美味的；可口的', 'Unit 7', 'The dinner is delicious.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'terrible', '糟糕的；可怕的', 'Unit 7', 'The weather is terrible.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'easy', '容易的；简单的', 'Unit 7', 'This math problem is easy.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'difficult', '困难的；艰难的', 'Unit 7', 'This English test is difficult.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'cheap', '便宜的；廉价的', 'Unit 7', 'This pen is cheap.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'expensive', '昂贵的；高价的', 'Unit 7', 'This dress is expensive.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'big', '大的；巨大的', 'Unit 7', 'This house is big.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'small', '小的；小', 'Unit 7', 'This car is small.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'long', '长的；长久的', 'Unit 7', 'This rope is long.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'short', '短的；矮的', 'Unit 7', 'This hair is short.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'tall', '高的；高大的', 'Unit 7', 'He is tall.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'short', '矮的；短的', 'Unit 7', 'She is short.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'fat', '胖的；肥的', 'Unit 7', 'The cat is fat.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'thin', '瘦的；薄的', 'Unit 7', 'The dog is thin.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'strong', '强壮的；坚强的', 'Unit 7', 'He is strong.', 'waiyanbanseven_b');
INSERT INTO words (wordlist_id, word, meaning_cn, unit, example1, source) VALUES (2, 'weak', '虚弱的；无力的', 'Unit 7', 'She is weak.', 'waiyanbanseven_b');
